### PR TITLE
Code for parralel attention

### PR DESCRIPTION
**Pull request by NohTow**
Implementation of #2.

I overwrote the existing classes to highlight the differences with the base architecture but it would obviously require a refactoring to make it prettier and let the option to choose between parallel and sequential attention (I was waiting for the big refactoring to make it compatible).
Notably ; maybe it's not that clean to forward the intermediate_ff as the result of the attention_block and merging it with the SwiGLU block might be better.

Also, after discussions with @ohallstrom (and @iacolippo on discord back then), we do not think it makes sense to implement it with post-norm, hence why I changed the code to pre-norm without adding flags.

### CODE REVIEW

**Comment by iacolippo** [comment]
we should still leave the option of sequential attention no?

**Comment by NohTow** [comment]
Yes, as I said I was mostly waiting for the refactoring to see how to properly let the user choose: use flags in the classes or create different ones.
Sorry it was not clear, I am editing the original comment.

**Comment by warner-benjamin** [comment]
@NohTow I have a flexible BERT implementation almost ready to go in the [flexbert branch](/AnswerDotAI/bert24/tree/flexbert). Should PR it later today after I do some more MLM cleanup and get classification working.

For fused parallel attention, you'd need to create a new `FlexBertUnpadFusedParallelPreNormLayer`, `FlexBertUnpadFusedParallelAttention`, and `FlexBertFusedParallelGLU` layers.

Let me know here or on discord if you have any questions.

**Comment by NohTow** [comment]
Thanks, I looked at it!
I'll recreate a branch and add those once we merge the flexbert branch into main.

**Pull request closed without merging**
